---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: board
spec:
  replicas: 4
  selector:
    matchLabels:
      app: board
  template:
    metadata:
      labels:
        app: board
    spec:
      containers:
      - name: board
        image: adijaiswal/boardgame:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000   # Use port 3000

---
apiVersion: v1
kind: Service
metadata:
  name: board-service
spec:
  selector:
    app: board
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80
    targetPort: 3000
  type: LoadBalancer
